### ISSUE TITLE
link fix!

### ISSUE THREAD

**Issue by josephofiowa** [meagdoh/meagdoh.github.io#7]
tiny FYI:

> Meag is a Senior UX Designer and Researcher at Agency CHIEF in Washington, D.C.

Agency CHIEF link is http://meagdoherty.io/www.agencychief.com causing 404. Update to href="www.agencychief.com" to https://www.agencychief.com :)

Love the site! Super impressive, direct, clean.

**Comment by meagdoh** [comment]
i missed this! Thanks @josephofiowa stay tuned for an upcoming re-design :)

**Comment by josephofiowa** [comment]
Woo!

**Comment by meagdoh** [comment]
1 year later - fixed link and updated design! http://meagdoherty.io/
